// Known-answer test vectors generated by tools/crypto-vectors/gen.js, an
// independent implementation of docs/PROTOCOL.md using libsodium-wrappers.
// Do not edit by hand; regenerate with `node gen.js`.

abstract final class CryptoTestVectors {
  static const String masterA =
      '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f';
  static const String masterB =
      '202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f';
  static const String aSign = 'FpjdRnzRhO3EVerRMUkfYpSlVFS1yGBYZ6YgnDB3ejo';
  static const String aBox = 'Zw82UvummJRp6Yq7KTgDsu-W9AgNUAj0gLVkRz2_-S8';
  static const String bSign = '-txVgxUZNiilSjrgMnqgWsYdgApLYjMP_kTUnsz8iOA';
  static const String bBox = 'M9_TSk4FOZb5GgJ4Xk-Ss90TFqeB64njuzFox58mUWU';
  static const String aCard =
      '{"v":1,"sign":"FpjdRnzRhO3EVerRMUkfYpSlVFS1yGBYZ6YgnDB3ejo","box":"Zw82UvummJRp6Yq7KTgDsu-W9AgNUAj0gLVkRz2_-S8","sig":"xGLCCJdSvrClwpIrrmPfgkQOQu1OU2uogaIXbace0KL5jXLgepbVSnKybf6dyld-2GYqzEQv4GdCnj3YCcTnCg"}';
  static const String safetyNumber =
      '86062 20299 29048 77658 05896 07373 64291 55246 85073 92264 61034 42656';
  static const String inner =
      '{"v":1,"from":"FpjdRnzRhO3EVerRMUkfYpSlVFS1yGBYZ6YgnDB3ejo","fromBox":"Zw82UvummJRp6Yq7KTgDsu-W9AgNUAj0gLVkRz2_-S8","to":"-txVgxUZNiilSjrgMnqgWsYdgApLYjMP_kTUnsz8iOA","ts":1791360000000,"n":"AAECAwQFBgcICQoLDA0ODw","type":"test.hello","body":{"text":"hello"}}';
  static const String innerSignature =
      '1yVxqZNm0wuo1yzL27NDsfeFqNx8-wn_Yyo9thdLF709gBEDkgSgWvFOhw_eIaIDz_tgQhklixq3cpDrfBIABw';
  static const String sealedAtoB =
      '5iihoODAjwpFOEMvGvVuZpzpF4lKDwkFn0Nm1p8_JEXN1Xo4ZbplhC-sCBCGxiv-DeYyDizfgbcZTBQ8aoKN0ugVpUHOAfqpom-YCOoNkx7_8gcqTCjQr45r-eQQDzkvKlABAw8b0sevz1Hu0Iiy__iIebTCFqSdnlWV1d0t0GSOOGfpAMOgSr1dz2RxldSAnOFYGGjklzR9ejzUODNkIYh8J0Tj1Js6YB_rm7nGRMvBCZE1qpd5UGe7tSnqOL3kmOTB60VvH35AQ_YYTfOMq3KJrKrWZhSIDPFu8ctRSWwhR8cjbUo_bpivv7-_1z5qiJb4BUUH62SYyys8qD0d5DNUrFBX0qG7cewgACTgRjvdeWtFo9DqGBRewyX5nQ8kBk8RHu3vDtn1GUsEbCgPpI0WOcBnvpy0NTrvX4dLCcyzXcC3yM4pN59m6e-U-94ze0Xn75G7NrGkxefKL9TmUnvvlkYubLl848oR3h6K-XeOIdI';

  /// Timestamp inside [inner].
  static const int innerTimestampMs = 1791360000000;
}
