import 'package:flutter/material.dart';

import '../../core/l10n/app_localizations.dart';
import 'chat_tokens.dart';

/// The emoji grid shown under the composer. A tap reports the emoji through
/// [onEmojiSelected]; the backspace key calls [onBackspace].
class EmojiPickerPanel extends StatefulWidget {
  const EmojiPickerPanel({
    super.key,
    required this.tokens,
    required this.onEmojiSelected,
    required this.onBackspace,
  });

  final ChatTokens tokens;
  final ValueChanged<String> onEmojiSelected;
  final VoidCallback onBackspace;

  @override
  State<EmojiPickerPanel> createState() => _EmojiPickerPanelState();
}

class _EmojiPickerPanelState extends State<EmojiPickerPanel>
    with SingleTickerProviderStateMixin {
  late final TabController _tabController;

  static const _categories = [
    (
      icon: Icons.sentiment_satisfied_alt_outlined,
      emojis: [
        '😀',
        '😃',
        '😄',
        '😁',
        '😆',
        '😅',
        '🤣',
        '😂',
        '🙂',
        '🙃',
        '😉',
        '😊',
        '😇',
        '🥰',
        '😍',
        '🤩',
        '😘',
        '😗',
        '😚',
        '😙',
        '😋',
        '😛',
        '😜',
        '🤪',
        '😝',
        '🤑',
        '🤗',
        '🤭',
        '🤫',
        '🤔',
        '🤐',
        '🤨',
        '😐',
        '😑',
        '😶',
        '😏',
        '😒',
        '🙄',
        '😬',
        '🤥',
        '😌',
        '😔',
        '😪',
        '🤤',
        '😴',
        '😷',
        '🤒',
        '🤕',
        '🤢',
        '🤮',
        '🤧',
        '🥵',
        '🥶',
        '🥴',
        '😵',
        '🤯',
        '🤠',
        '🥳',
        '🥸',
        '😎',
        '🤓',
        '🧐',
        '😕',
        '😟',
        '🙁',
        '☹️',
        '😮',
        '😯',
        '😲',
        '😳',
        '🥺',
        '😦',
        '😧',
        '😨',
        '😰',
        '😥',
        '😢',
        '😭',
        '😱',
        '😖',
        '😣',
        '😞',
        '😓',
        '😩',
        '😫',
        '🥱',
        '😤',
        '😡',
        '😠',
        '🤬',
        '💀',
        '💩',
        '🤡',
        '👻',
        '👽',
        '🤖',
      ],
    ),
    (
      icon: Icons.front_hand_outlined,
      emojis: [
        '👋',
        '🤚',
        '🖐️',
        '✋',
        '🖖',
        '🤙',
        '👈',
        '👉',
        '👆',
        '🖕',
        '👇',
        '☝️',
        '👍',
        '👎',
        '✊',
        '👊',
        '🤛',
        '🤜',
        '👏',
        '🙌',
        '👐',
        '🤲',
        '🤝',
        '🙏',
        '✍️',
        '💅',
        '🤳',
        '💪',
        '🦾',
        '🦿',
        '🦵',
        '🦶',
        '👂',
        '🦻',
        '👃',
        '🧠',
        '🫀',
        '🫁',
        '🦷',
        '🦴',
        '👀',
        '👁️',
        '👅',
        '👄',
        '👶',
        '🧒',
        '👦',
        '👧',
        '🧑',
        '👱',
        '👨',
        '🧔',
        '👩',
        '🧓',
        '👴',
        '👵',
        '🙍',
        '🙎',
        '🙅',
        '🙆',
        '💁',
        '🙋',
        '🧏',
        '🙇',
        '🤦',
        '🤷',
        '🧑‍⚕️',
        '🧑‍🎓',
        '🧑‍🏫',
        '🧑‍⚖️',
        '🧑‍🌾',
        '🧑‍🍳',
      ],
    ),
    (
      icon: Icons.pets_outlined,
      emojis: [
        '🐶',
        '🐱',
        '🐭',
        '🐹',
        '🐰',
        '🦊',
        '🐻',
        '🐼',
        '🐨',
        '🐯',
        '🦁',
        '🐮',
        '🐷',
        '🐽',
        '🐸',
        '🐵',
        '🙈',
        '🙉',
        '🙊',
        '🐒',
        '🐔',
        '🐧',
        '🐦',
        '🐤',
        '🐣',
        '🐥',
        '🦆',
        '🦅',
        '🦉',
        '🦇',
        '🐺',
        '🐗',
        '🐴',
        '🦄',
        '🐝',
        '🐛',
        '🦋',
        '🐌',
        '🐞',
        '🐜',
        '🦟',
        '🐢',
        '🐍',
        '🦎',
        '🐙',
        '🦑',
        '🦐',
        '🦞',
        '🦀',
        '🐡',
        '🐠',
        '🐟',
        '🐬',
        '🐳',
        '🐋',
        '🦈',
        '🐊',
        '🐅',
        '🐆',
        '🦓',
        '🐘',
        '🦛',
        '🦏',
        '🐪',
        '🐫',
        '🦒',
        '🦘',
        '🌲',
        '🌳',
        '🌴',
        '🌵',
        '🌱',
        '🌿',
        '🍀',
        '🍁',
        '🍂',
        '🍃',
        '🌸',
        '💮',
        '🌹',
        '🌺',
        '🌻',
        '🌼',
        '🌷',
      ],
    ),
    (
      icon: Icons.fastfood_outlined,
      emojis: [
        '🍏',
        '🍎',
        '🍐',
        '🍊',
        '🍋',
        '🍌',
        '🍉',
        '🍇',
        '🍓',
        '🫐',
        '🍈',
        '🍒',
        '🍑',
        '🥭',
        '🍍',
        '🥥',
        '🥝',
        '🍅',
        '🍆',
        '🥑',
        '🥦',
        '🥬',
        '🥒',
        '🌶️',
        '🌽',
        '🥕',
        '🧄',
        '🧅',
        '🥔',
        '🍠',
        '🥐',
        '🍞',
        '🥖',
        '🥨',
        '🧀',
        '🥚',
        '🍳',
        '🧈',
        '🥞',
        '🧇',
        '🥓',
        '🥩',
        '🍗',
        '🍖',
        '🌭',
        '🍔',
        '🍟',
        '🍕',
        '🥪',
        '🥙',
        '🌮',
        '🌯',
        '🥗',
        '🥘',
        '🥫',
        '🍝',
        '🍜',
        '🍲',
        '🍛',
        '🍣',
        '🍱',
        '🥟',
        '🍤',
        '🍙',
        '🍚',
        '🍢',
        '🍡',
        '🍧',
        '🍨',
        '🍦',
        '🍰',
        '🎂',
        '🍮',
        '🍭',
        '🍬',
        '🍫',
        '🍿',
        '🍩',
        '🍪',
        '🌰',
        '🥜',
        '🥛',
        '☕',
        '🫖',
      ],
    ),
    (
      icon: Icons.sports_soccer_outlined,
      emojis: [
        '⚽',
        '🏀',
        '🏈',
        '⚾',
        '🥎',
        '🎾',
        '🏐',
        '🏉',
        '🥏',
        '🎱',
        '🪀',
        '🏓',
        '🏸',
        '🏒',
        '🏑',
        '🏏',
        '🥅',
        '⛳',
        '🪁',
        '🏹',
        '🎣',
        '🥊',
        '🥋',
        '🛹',
        '🛼',
        '🛷',
        '⛸️',
        '🎿',
        '🏂',
        '🏋️',
        '🤼',
        '🤸',
        '⛹️',
        '🤺',
        '🏄',
        '🏊',
        '🤽',
        '🚣',
        '🧗',
        '🚵',
        '🚴',
        '🏆',
        '🥇',
        '🥈',
        '🥉',
        '🏅',
        '🎖️',
        '🎗️',
        '🎫',
        '🎟️',
        '🎪',
        '🎭',
        '🎨',
        '🎬',
        '🎤',
        '🎧',
        '🎼',
        '🎵',
        '🎶',
        '🥁',
        '🎷',
        '🎺',
        '🎸',
        '🎻',
        '🎲',
        '♟️',
        '🎯',
        '🎳',
        '🎮',
        '🎰',
        '🧩',
        '🃏',
      ],
    ),
    (
      icon: Icons.directions_car_outlined,
      emojis: [
        '🚗',
        '🚕',
        '🚙',
        '🚌',
        '🚎',
        '🏎️',
        '🚓',
        '🚑',
        '🚒',
        '🚐',
        '🚚',
        '🚛',
        '🚜',
        '🛴',
        '🚲',
        '🛵',
        '🏍️',
        '🛺',
        '🚨',
        '🚔',
        '🚍',
        '🚘',
        '🚖',
        '🚡',
        '🚠',
        '🚟',
        '🚃',
        '🚋',
        '🚞',
        '🚝',
        '🚄',
        '🚅',
        '🚈',
        '🚂',
        '🚆',
        '🚇',
        '🚊',
        '🚉',
        '✈️',
        '🛫',
        '🛬',
        '💺',
        '🛰️',
        '🚀',
        '🛸',
        '🚁',
        '🛶',
        '⛵',
        '🚤',
        '🛳️',
        '⛴️',
        '🚢',
        '⚓',
        '⛽',
        '🚧',
        '🚥',
        '🚦',
        '🛑',
        '🗼',
        '🗽',
        '⛪',
        '🕌',
        '🛕',
        '🕍',
        '⛩️',
        '🕋',
        '⛲',
        '⛺',
        '🌁',
        '🌃',
        '🏙️',
        '🌄',
      ],
    ),
    (
      icon: Icons.lightbulb_outlined,
      emojis: [
        '⌚',
        '📱',
        '📲',
        '💻',
        '⌨️',
        '🖥️',
        '🖨️',
        '🖱️',
        '🕹️',
        '💾',
        '💿',
        '📀',
        '📷',
        '📸',
        '📹',
        '🎥',
        '📽️',
        '📞',
        '☎️',
        '📟',
        '📠',
        '📺',
        '📻',
        '🎙️',
        '⏱️',
        '⏲️',
        '⏰',
        '🕰️',
        '⌛',
        '⏳',
        '📡',
        '🔋',
        '🔌',
        '💡',
        '🔦',
        '🕯️',
        '🧯',
        '💸',
        '💵',
        '💴',
        '💶',
        '💷',
        '🪙',
        '💰',
        '💳',
        '💎',
        '⚖️',
        '🧰',
        '🔧',
        '🔨',
        '⚒️',
        '🛠️',
        '⛏️',
        '🪓',
        '🔩',
        '⚙️',
        '🧲',
        '🔫',
        '💣',
        '🔪',
        '🛡️',
        '🔮',
        '📿',
        '💈',
        '🔬',
        '🔭',
        '🩺',
        '💊',
        '💉',
        '🩹',
        '🧬',
        '🔑',
      ],
    ),
    (
      icon: Icons.favorite_outline,
      emojis: [
        '❤️',
        '🧡',
        '💛',
        '💚',
        '💙',
        '💜',
        '🖤',
        '🤍',
        '🤎',
        '💔',
        '❤️‍🔥',
        '❤️‍🩹',
        '💕',
        '💞',
        '💓',
        '💗',
        '💖',
        '💘',
        '💝',
        '💟',
        '☮️',
        '✝️',
        '☪️',
        '🕉️',
        '☸️',
        '✡️',
        '🔯',
        '🕎',
        '☯️',
        '☦️',
        '🛐',
        '⛎',
        '♈',
        '♉',
        '♊',
        '♋',
        '♌',
        '♍',
        '♎',
        '♏',
        '♐',
        '♑',
        '♒',
        '♓',
        '🆔',
        '⚛️',
        '🉑',
        '📴',
        '📳',
        '🈶',
        '🈚',
        '🈸',
        '🈺',
        '🈷️',
        '✴️',
        '📶',
        '🈹',
        '🈲',
        '🔞',
        '🔟',
        '🔤',
        '🔢',
        '🔣',
        '🔲',
        '🔳',
        '🔴',
        '🟠',
        '🟡',
        '🟢',
        '🔵',
        '🟣',
        '⚫',
        '⚪',
        '🟥',
        '🟧',
        '🟨',
        '🟩',
        '🟦',
        '🟪',
        '⬛',
        '⬜',
        '🔶',
        '🔷',
        '🔸',
        '🔹',
        '🔺',
        '🔻',
        '💠',
        '🔘',
        '🏁',
        '🚩',
        '🎌',
        '🏴',
        '🏳️',
        '✨',
        '⭐',
        '🌟',
        '💫',
        '⚡',
        '☄️',
        '💥',
        '🔥',
        '🎉',
        '🎊',
        '🎈',
        '🎁',
        '💯',
        '✅',
      ],
    ),
  ];

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: _categories.length, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    // In the order of [_categories].
    final labels = [
      l10n.chatEmojiSmileys,
      l10n.chatEmojiPeople,
      l10n.chatEmojiAnimals,
      l10n.chatEmojiFood,
      l10n.chatEmojiActivities,
      l10n.chatEmojiTravel,
      l10n.chatEmojiObjects,
      l10n.chatEmojiSymbols,
    ];
    return Container(
      height: 270,
      decoration: BoxDecoration(
        color: widget.tokens.footer,
        border: Border(top: BorderSide(color: widget.tokens.divider)),
      ),
      child: Column(
        children: [
          Expanded(
            child: TabBarView(
              controller: _tabController,
              children: [
                for (final cat in _categories)
                  GridView.builder(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 8,
                      vertical: 8,
                    ),
                    gridDelegate:
                        const SliverGridDelegateWithMaxCrossAxisExtent(
                          maxCrossAxisExtent: 46,
                          mainAxisSpacing: 4,
                          crossAxisSpacing: 4,
                          childAspectRatio: 1.0,
                        ),
                    itemCount: cat.emojis.length,
                    itemBuilder: (context, index) {
                      final emoji = cat.emojis[index];
                      return Material(
                        color: Colors.transparent,
                        child: InkWell(
                          borderRadius: BorderRadius.circular(8),
                          onTap: () => widget.onEmojiSelected(emoji),
                          child: Center(
                            child: Text(
                              emoji,
                              style: const TextStyle(
                                fontSize: 26,
                                fontFamilyFallback: [
                                  'Apple Color Emoji',
                                  'Segoe UI Emoji',
                                  'Noto Color Emoji',
                                ],
                              ),
                            ),
                          ),
                        ),
                      );
                    },
                  ),
              ],
            ),
          ),
          Container(
            height: 44,
            decoration: BoxDecoration(
              color: widget.tokens.footer,
              border: Border(
                top: BorderSide(
                  color: widget.tokens.divider.withValues(alpha: 0.5),
                ),
              ),
            ),
            child: Row(
              children: [
                Expanded(
                  child: TabBar(
                    controller: _tabController,
                    isScrollable: true,
                    tabAlignment: TabAlignment.start,
                    indicatorColor: widget.tokens.sendFill,
                    indicatorSize: TabBarIndicatorSize.label,
                    labelColor: widget.tokens.sendFill,
                    unselectedLabelColor: widget.tokens.attachIcon,
                    dividerColor: Colors.transparent,
                    padding: EdgeInsets.zero,
                    labelPadding: const EdgeInsets.symmetric(horizontal: 10),
                    tabs: [
                      for (final (i, cat) in _categories.indexed)
                        Tab(
                          icon: Tooltip(
                            message: labels[i],
                            child: Icon(cat.icon, size: 22),
                          ),
                        ),
                    ],
                  ),
                ),
                IconButton(
                  tooltip: l10n.chatEmojiBackspace,
                  icon: Icon(
                    Icons.backspace_outlined,
                    color: widget.tokens.attachIcon,
                    size: 22,
                  ),
                  onPressed: widget.onBackspace,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
